[build]
  command = "npm run build"
  publish = "dist"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = []}

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Custom Domain Configuration
[context.production]
  environment = { URL = "https://mycip.ca", NODE_ENV = "production" }

# Domain Configuration
[[redirects]]
  from = "https://www.mycip.ca/*"
  to = "https://mycip.ca/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://mycip.ca/*"
  to = "https://mycip.ca/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.mycip.ca/*"
  to = "https://mycip.ca/:splat"
  status = 301
  force = true

# Specific page redirects should come before catch-all
[[redirects]]
  from = "/province/*"
  to = "/index.html"
  status = 200
  conditions = {Role = []}

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200
  conditions = {Role = []}

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  conditions = {Role = []}

# Remove the problematic admin/country condition from catch-all
[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    Content-Security-Policy = """
      default-src 'none';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://images.unsplash.com https://upload.wikimedia.org;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.bigdatacloud.net;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      upgrade-insecure-requests;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Resource-Policy = "same-origin"
    Feature-Policy = "camera 'none'; microphone 'none'; geolocation 'none'"
    Expect-CT = "max-age=86400, enforce"
    NEL = """
      {"report_to": "default", "max_age": 31536000, "include_subdomains": true}
    """
    Report-To = """
      {"group": "default", "max_age": 31536000, "endpoints": [{"url": "https://mycip.ca/_report"}], "include_subdomains": true}
    """

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"